media:
  input: public/media
  output: /media
  rename: safe
  categories: [image]

components:
  socialMedia:
    type: object
    fields:
      - name: facebook
        label: Facebook
        type: string

      - name: instagram
        label: Instagram
        type: string

      - name: youtube
        label: YouTube
        type: string

content:
  # HOME
  - name: home
    label: Home
    type: file
    path: content/home.json
    format: json
    operations:
      delete: false
    fields:
      - name: title
        label: Title
        type: string

      - name: biography
        label: Biography
        type: rich-text

  # REPERTOIRE
  - name: repertoire
    label: Repertoire
    type: file
    path: content/repertoire.json
    format: json
    operations:
      delete: false
    fields:
      - name: entries
        label: Repertoire
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{composer} - {piece}"
        fields:
          - name: type
            label: Type of Music
            type: select
            options:
              values:
                - Opera
                - Chamber
                - Sacral

          - name: composer
            label: Composer
            type: string

          - name: piece
            label: Piece
            type: string

          - name: role
            label: Lovisa's Role
            type: string

  # EVENTS
  - name: events
    label: Events
    type: collection
    path: content/events
    format: json
    filename: "{date}-{name}.json"
    view:
      fields: [date, name, time]
      primary: name
      sort: [date, name]
      default:
        sort: date
        order: desc
    fields:
      - name: date
        label: Date
        type: date

      - name: time
        label: Time
        type: string

      - name: name
        label: Event Name
        type: string

      - name: description
        label: Description
        type: rich-text

      - name: link
        label: Link
        type: string

  # MEDIA GROUP
  - name: mediaSection
    label: Media
    type: group
    items:

      - name: videos
        label: Videos
        type: collection
        path: content/videos
        format: json
        filename: "{title}.json"
        view:
          fields: [title, youtubeLink]
          primary: title
        fields:
          - name: youtubeLink
            label: YouTube Link
            type: string

          - name: title
            label: Title
            type: string

          - name: description
            label: Description
            type: text

      - name: photos
        label: Photos
        type: file
        path: content/photos.json
        format: json
        operations:
          delete: false
        fields:
          - name: portraits
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{caption}"
            fields:
              - name: image
                label: Image
                type: image

              - name: caption
                label: Caption
                type: string

          - name: onStage
            label: On Stage
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{caption}"
            fields:
              - name: image
                label: Image
                type: image

              - name: caption
                label: Caption
                type: string

  # CONTACT
  - name: contact
    label: Contact
    type: file
    path: content/contact.json
    format: json
    operations:
      delete: false
    fields:
      - name: agency
        label: Agency
        type: object
        fields:
          - name: name
            label: Name
            type: string

          - name: email
            label: Email
            type: string

          - name: phone
            label: Phone
            type: string

      - name: lovisa
        label: Lovisa
        type: object
        fields:
          - name: name
            label: Name
            type: string

          - name: email
            label: Email
            type: string

          - name: phone
            label: Phone
            type: string

      - name: socialMedia
        component: socialMedia

actions:
  - name: deploy-site
    label: Deploy Site
    workflow: pages-cms-action.yml