media:
  input: public/media
  output: /media
  rename: safe
  categories: [image]

components:
  socialMedia:
    type: object
    fields:
      - name: facebook
        label: Facebook
        type: string

      - name: instagram
        label: Instagram
        type: string

      - name: youtube
        label: YouTube
        type: string

content:
  # HOME
  - name: home
    label: Home
    type: file
    path: content/home.json
    format: json
    operations:
      delete: false
    fields:
      - name: title
        type: string

      - name: biography
        type: rich-text

  # REPERTOIRE
  - name: repertoire
    label: Repertoire
    type: file
    path: content/repertoire.json
    format: json
    operations:
      delete: false
    fields:
      - name: entries
        label: Repertoire
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{composer} - {piece}"
        fields:
          - name: type
            label: Type of Music
            type: select
            options:
              values:
                - Opera
                - Chamber
                - Sacral

          - name: composer
            type: string

          - name: piece
            type: string

          - name: role
            label: Role
            type: string

  # PROGRAMMES
  - name: programmes
    label: Programmes
    type: collection
    path: content/programmes
    format: json
    filename: "{title}.json"
    view:
      primary: title
    fields:
      - name: title
        type: string

      - name: description
        type: rich-text

      - name: images
        label: Images
        type: image
        options:
          multiple: true

      - name: repertoire
        label: Repertoire
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{composer} - {piece}"
        fields:
          - name: composer
            type: string

          - name: piece
            type: string

  # EVENTS
  - name: events
    label: Events
    type: collection
    path: content/events
    format: json
    filename: "{date}-{name}.json"
    view:
      primary: name
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: date
        type: date

      - name: time
        label: Time of Day
        type: string

      - name: name
        label: Event Name
        type: string

      - name: description
        type: rich-text

      - name: link
        type: string

      - name: programme
        label: Programme
        type: reference
        options:
          collection: programmes

  # MEDIA GROUP
  - name: mediaSection
    label: Media
    type: group
    items:

      - name: videos
        label: Videos
        type: collection
        path: content/videos
        format: json
        filename: "{title}.json"
        view:
          primary: title
        fields:
          - name: youtubeLink
            label: YouTube Link
            type: string

          - name: title
            type: string

          - name: description
            type: text

      - name: photos
        label: Photos
        type: file
        path: content/photos.json
        format: json
        operations:
          delete: false
        fields:
          - name: portraits
            label: Portraits
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{caption}"
            fields:
              - name: image
                type: image

              - name: caption
                type: string

          - name: onStage
            label: On Stage
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{caption}"
            fields:
              - name: image
                type: image

              - name: caption
                type: string

  # CONTACT
  - name: contact
    label: Contact
    type: file
    path: content/contact.json
    format: json
    operations:
      delete: false
    fields:
      - name: agency
        label: Agency
        type: object
        fields:
          - name: name
            type: string

          - name: email
            type: string

          - name: phone
            type: string

      - name: lovisa
        label: Lovisa
        type: object
        fields:
          - name: name
            type: string

          - name: email
            type: string

          - name: phone
            type: string

      - name: socialMedia
        label: Social Media
        component: socialMedia

actions:
  - name: deploy-site
    label: Deploy Site
    workflow: pages-cms-action.yml